---
kind: pipeline
name: test

steps:

  - name: shellcheck
    image: python:3-alpine
    commands:
      - apk add shellcheck
      - make all

  - name: notify
    image: drillster/drone-email
    settings:
      host:
        from_secret: SMTP_HOST  # pragma: whitelist secret
      username:
        from_secret: SMTP_USER  # pragma: whitelist secret
      password:
        from_secret: SMTP_PASS  # pragma: whitelist secret
      from: drone@iamthefij.com
    when:
      status: [changed, failure]
