---
- id: docker-compose-check
  name: Validate docker compose files
  description: Checks that docker compose files are valid
  language: script
  entry: compose-check.sh
  files: (docker-)?compose.y[a]{0,1}ml$
